---
- name: EDID Config - Read the current EDID file
  ansible.builtin.slurp:
    src: /etc/kvmd/tc358743-edid.hex
  register: current_edid

- name: EDID Config - Decode current EDID content
  ansible.builtin.set_fact:
    decoded_current_edid: "{{ current_edid.content | b64decode }}"

- name: EDID Config - Set EDID to default value
  when: (hdmi.edid.custom | default("") | length == 0)
  block:
    - name: EDID Config - Read the default EDID file
      ansible.builtin.slurp:
        src: "/usr/share/kvmd/configs.default/kvmd/edid/{{ pikvm_version_mapped }}.hex"
      register: default_edid

    - name: EDID Config - Set current EDID value to default
      when: (decoded_current_edid != default_edid.content | b64decode)
      block:
        - name: EDID Config - Mount filesystem Read Write (rw)
          ansible.builtin.import_tasks: shared/filesystem-mode.yml
          vars:
            fs_mode: rw

        - name: Copy default EDID to destination if it does not match current
          ansible.builtin.copy:
            content: "{{ default_edid.content | b64decode }}"
            dest: /etc/kvmd/tc358743-edid.hex
            mode: "0640"
            force: true
          notify: Reboot PiKVM

- name: EDID Config - Set EDID to custom value
  when: >
    (hdmi.edid.custom | default("") | length > 0)
    and (hdmi.edid.custom != decoded_current_edid)
  block:
    - name: EDID Config - Mount filesystem Read Write (rw)
      ansible.builtin.import_tasks: shared/filesystem-mode.yml
      vars:
        fs_mode: rw

    - name: EDID Config - Override tc358743-edid hex file with custom EDID value if not the same
      ansible.builtin.copy:
        content: "{{ hdmi.edid.custom }}"
        dest: /etc/kvmd/tc358743-edid.hex
        mode: "0640"
        force: true
      notify: Reboot PiKVM
