---
- name: Validate System
  ansible.builtin.import_tasks: validate/system-validate.yml

- name: Update all system packages
  ansible.builtin.import_tasks: system-updates.yml

- name: Configure PiKVM Physical OLED Screen
  ansible.builtin.import_tasks: oled-config.yml

- name: Configure PiKVM Physical Fan
  ansible.builtin.import_tasks: fan-config.yml

- name: Manage web terminal
  ansible.builtin.import_tasks: web-terminal-config.yml

- name: Configure EDID file
  ansible.builtin.import_tasks: edid-config.yml
  vars:
    pikvm_version: "{{ pikvm_version_mapped }}"

- name: Configure KVMD Override
  ansible.builtin.import_tasks: kvmd-override-config.yml
  vars:
    pikvm_version: "{{ pikvm_version_mapped }}"
  when: (kvmd_override_enabled | bool)

- name: Force mount filesystem Read Write (ro)
  ansible.builtin.import_tasks: shared/filesystem-mode.yml
  vars:
    fs_mode: ro
