---
# TODO update validate_certs check when certificates are enabled
# TODO update X-KVMD user and password on existing credentials
- name: Prometheus Validate - Check if Prometheus metrics endpoint is accessible
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/export/prometheus/metrics"
    method: GET
    status_code: 200
    timeout: 10
    headers:
      X-KVMD-User: "admin"
      X-KVMD-Passwd: "admin"
    validate_certs: false
  register: prometheus_check
  failed_when: false

- name: Prometheus Validate - Display status of Prometheus metrics endpoint
  ansible.builtin.debug:
    msg: >-
      {{
        'Prometheus metrics endpoint successfully validated.' if prometheus_check.status == 200
        else 'Prometheus metrics endpoint unsuccessfully validated.'
      }}
  failed_when: >
    (prometheus_check.status != 200)
    and (validate_fail_on_error)
